# Generated by Django 3.2.23 on 2024-01-15 21:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HangmanModel',
            fields=[
                ('sessionId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answer', models.TextField()),
                ('numberOfAttempts', models.PositiveSmallIntegerField(default=0)),
                ('maxNumberOfAttempts', models.PositiveSmallIntegerField()),
                ('currentAnswer', models.TextField()),
                ('result', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('WIN', 'Win'), ('LOSE', 'Lose')], default='IN_PROGRESS', max_length=11)),
            ],
        ),
    ]
